### ISSUE TITLE
Xiaomi Aqara button

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#11]
Hi! Me again..

I hope you can add support for this sensor.. I allready added someone to homey with your addon, but it seems this one is just a different one.. The one that is supported has ID: WXKG11LM, the one I am not able to connect is the WXKG12LM. I think the difference is that the latest one has also a shake sensor in it.

Here is a link: https://www.aliexpress.com/item/32924164840.html

I have no other information. If you need more, please let me know.

Best regards,
Marcel

**Comment by powermarcel10** [comment]
Hi here is some more information about the button with number WXKG12LM

Single press:

2019-12-05 14:03:57 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '78',
  r: 'sensors',
  state: { buttonevent: 1002, lastupdated: '2019-12-05T13:03:57' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:90:df:fe-01-0006' }

Double press:

2019-12-05 14:01:20 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '78',
  r: 'sensors',
  state: { buttonevent: 1004, lastupdated: '2019-12-05T13:01:20' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:90:df:fe-01-0006' }

Long press:

2019-12-05 14:02:24 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '78',
  r: 'sensors',
  state: { buttonevent: 1003, lastupdated: '2019-12-05T13:02:24' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:90:df:fe-01-0006' }

Shake:

2019-12-05 14:00:12 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '78',
  r: 'sensors',
  state: { buttonevent: 1007, lastupdated: '2019-12-05T13:00:12' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:90:df:fe-01-0006' }

Cheers,
Marcel

**Comment by notabene00** [comment]
The one that is supported is `lumi.sensor_switch.aq2`. What modelid of the second?

**Comment by powermarcel10** [comment]
lumi.sensor_swit

**Comment by powermarcel10** [comment]
Aqara Wireless switch (Gyro)

**Comment by notabene00** [comment]
> lumi.sensor_swit

`lumi.sensor_switch`?

**Comment by powermarcel10** [comment]
That should make more sense but it't really saying lumi.sensor_swit in homey developer tools.
![swit](https://user-images.githubusercontent.com/2340835/70241639-ac6f3780-176f-11ea-9e82-bfb2b349720a.jpg)

**Comment by notabene00** [comment]
Ok
https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-buttons
Let's give it a try

**Comment by notabene00** [comment]
ah, if you have paired aqara buttons before, you should re-pair them
it's still one driver but now for both button types
and it using data that cannot be in the previously paired devices

**Comment by powermarcel10** [comment]
Its not working yet. It only discovers the old one wich I removed first. WXKG12LM is not there yet.

**Comment by notabene00** [comment]
Are you trying the [aqara-buttons](https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-buttons) branch?

**Comment by powermarcel10** [comment]
Yes I do. I can also see now the "shake" option in the IF colum in homey. Only the WXKG11LM has no support for it, but yes Im using the right branche.

**Comment by SkorpionNL** [comment]
> The one that is supported is `lumi.sensor_switch.aq2`. What modelid of the second?

I think it is `lumi.sensor_switch.aq3`

**Comment by notabene00** [comment]
I thought about it
Changed
@powermarcel10 [bump](https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-buttons)

**Comment by notabene00** [comment]
> I can also see now the "shake" option in the IF column in homey. Only the WXKG11LM has no support for it

I just figured out that it cannot be done with one device
`device.js` file contains only trigger's handler
the triggers themselves are stored in the `app.json`
so we can't have one device with two (programmatically assigned) different sets of triggers

but you still can try to pair `lumi.sensor_switch.aq3`

**Comment by notabene00** [comment]
- [x] `aqara-button` fully reverted
- [x] `aqara-button-gyro` added as a separate device
- [x] version bump
- [x] test
- [x] merge

**Comment by powermarcel10** [comment]
> * [x]  `aqara-button` fully reverted
> * [x]  `aqara-button-gyro` added as a separate device
> * [x]  version bump
> * [ ]  test
> * [ ]  merge

I have tested this new version, but the app keeps crashing. Installed the master branch again, everything fine, Install the new test branch, and it crashes. Tried 2 times.

**Comment by powermarcel10** [comment]
NOOOOOO all devices are broken now.. Rebooting homey now.. I hope my devices come back online...

**Comment by notabene00** [comment]
@powermarcel10 reinstall version from master branch and all should be ok

**Comment by powermarcel10** [comment]
Back online.. Thank God. :p Had to reboot homey after installing master. But not its fine. Im only not able to remove the gyro switch. It keeps trying to get connection wich is not possible with the current master branch offcourse..

Any idea what goes wrong with the test branch?

**Comment by powermarcel10** [comment]
I will try it one more time and see what a reboot does with the test branch.

**Comment by notabene00** [comment]
> Any idea what goes wrong

I just tested [aqara-buttons](https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-buttons) and it is not crashing during normal use. Is it broke during adding new buttons? Can you post stacktrace here?

**Comment by powermarcel10** [comment]
Did some more testing.. After reinstalling the test branch again, the app keeps crashing but I was able to remove the gyra switch. Than did a reboot of homey and everything was working fine. Than, installed the gyro switch again, and the app was crashing again. So it most have something to do with the added code.

**Comment by notabene00** [comment]
@powermarcel10 tester needed
check out last changes

**Comment by powermarcel10** [comment]
Sorry, same problem!

**Comment by SkorpionNL** [comment]
Can you put your debug output here when it crashes? @powermarcel10

**Comment by powermarcel10** [comment]
Sure I will.. Can you please tell me how? I only know how to create a diagnostic report in Homey for Athom..

**Comment by powermarcel10** [comment]
Aaaah just with cli I think.. Let me try..

**Comment by SkorpionNL** [comment]
Yes, via CLI. `athom app run` and then copy then output when it crashes.

**Comment by powermarcel10** [comment]
Microsoft Windows [Version 10.0.18362.476]
(c) 2019 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\power>cd C:\CLI\HomeyCONZ-aqara-buttons\HomeyCONZ-aqara-buttons

C:\CLI\HomeyCONZ-aqara-buttons\HomeyCONZ-aqara-buttons>homey app install
✓ Pre-processing app...
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
 — App size: 861.5 KB
✓ Installing Homey App on `Homey` (http://192.168.0.131:80)...
✓ Homey App `ru.notabene.deconz` successfully installed

C:\CLI\HomeyCONZ-aqara-buttons\HomeyCONZ-aqara-buttons>homey app run
✓ Pre-processing app...
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
 — App size: 861.5 KB
✓ Installing Homey App on `Homey` (http://192.168.0.131:80)...
✓ Homey App `ru.notabene.deconz` successfully installed
✓ Running `ru.notabene.deconz`, press CTRL+C to quit
 — Profile your app's performance at https://go.athom.com/app-profiling?homey=5808953c1b4ad29575d05156&app=ru.notabene.deconz
─────────────── Logging stdout & stderr ───────────────
2019-12-06 22:50:30 [log] [deCONZ] Websocket connect...
2019-12-06 22:50:31 [log] [deCONZ] Websocket is up
2019-12-06 22:50:33 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '3',
  r: 'sensors',
  state:
   { current: 31,
     lastupdated: '2019-12-06T21:50:31',
     power: 3,
     voltage: 242 },
  t: 'event',
  uniqueid: '00:15:8d:00:03:28:33:f6-01-0b04' }
2019-12-06 22:50:34 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '61',
  r: 'sensors',
  state: { lastupdated: '2019-12-06T21:50:31', presence: true },
  t: 'event',
  uniqueid: '00:17:88:01:04:b7:cc:a7-02-0406' }
2019-12-06 22:50:34 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '63',
  r: 'sensors',
  state:
   { dark: true,
     daylight: false,
     lastupdated: '2019-12-06T21:50:31',
     lightlevel: 4895,
     lux: 3 },
  t: 'event',
  uniqueid: '00:17:88:01:04:b7:cc:a7-02-0400' }
2019-12-06 22:50:35 [log] [ManagerDrivers] [tradfri-square-dimmer] TradfriSquareDimmerDriver has been inited
2019-12-06 22:50:35 [log] [ManagerDrivers] [sensor_smoke] SmokeDriver has been initiated
2019-12-06 22:50:35 [log] [ManagerDrivers] [mi-magnet] MiMagnetDriver has been initiated
2019-12-06 22:50:36 [log] [ManagerDrivers] [aqara-button-gyro] AqaraButtonGyroDriver has been initiated
2019-12-06 22:50:36 [log] [ManagerDrivers] [mi-button] MiButtonDriver has been initiated
2019-12-06 22:50:36 [log] [ManagerDrivers] [tradfri-wireless-dimmer] TradfriWirelessDimmerDriver has been inited
2019-12-06 22:50:36 [log] [ManagerDrivers] [symfonisk-remote] SymfoniskRemoteDriver has been initiated
2019-12-06 22:50:36 [log] [ManagerDrivers] [tradfri-motion-sensor] TradfriMotionSensorDriver has been initiated
2019-12-06 22:50:36 [log] [ManagerDrivers] [leakage_aq1] LeakageDriver has been initiated
2019-12-06 22:50:36 [log] [ManagerDrivers] [blinds] BlindsDriver has been initiated
2019-12-06 22:50:36 [log] [ManagerDrivers] [mijia-temphum] MijiaTempHumDriver has been initiated
2019-12-06 22:50:36 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '69',
  r: 'sensors',
  state:
   { buttonevent: 7000,
     gesture: 0,
     lastupdated: '2019-12-06T21:50:34' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:89:d2:14-02-0012' }
2019-12-06 22:50:36 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '70',
  r: 'sensors',
  state:
   { buttonevent: 8816,
     gesture: 7,
     lastupdated: '2019-12-06T21:50:35' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:89:d2:14-03-000c' }
2019-12-06 22:50:40 [log] [ManagerDrivers] [tradfri-remote-control] TradfriRemoteControlDriver has been inited
2019-12-06 22:50:40 [log] [ManagerDrivers] [tradfri-remote-control] [0] TRÅDFRI remote control has been inited
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] AqaraMagnetDriver has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] [0] Voordeur has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] [1] Halkastdeur has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] [2] Brievenbus has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] [3] Keukenkastdeur has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] [4] Schuurdeur has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] [5] Achterdeur has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-magnet] [6] Zolderdeur has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-cube] CubeDriver has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-cube] [0] Mi Magic Cube has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-button] AqaraButtonDriver has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-button] [0] Keukenschakelaar has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] LampDriver has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [0] Overlooplamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [1] Hallamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [2] Buitenlamp voor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [3] Eettafellamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [4] Afzuigkap has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [5] Kledingkamerlamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [6] WC lamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [7] Bedlamp Mars has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [8] Bedlamp Suus has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [9] Badkamerlamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [10] Logeerkamerlamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [11] Sfeerlamp has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [12] Spot links has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [13] Spot midden has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [14] Spot rechts has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [15] Zolder spot 1 has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [lamp] [16] Zolder spot 2 has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [mi-motion] MiMotionDriver has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [mi-motion] [0] Wc sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [mi-motion] [1] Badkamer sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [mi-motion] [2] Logeerkamer sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [hue-motion-sensor] HueMotionDriver has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [hue-motion-sensor] [0] Hue woonkamer sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [hue-motion-sensor] [1] Hue keuken sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [hue-motion-sensor] [2] Overloop sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [hue-motion-sensor] [3] Hue badkamer sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [hue-motion-sensor] [4] Hue slaapkamer sensor has been initiated
2019-12-06 22:50:40 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '13',
  r: 'sensors',
  state:
   { current: 0,
     lastupdated: '2019-12-06T21:50:39',
     power: 0,
     voltage: 243 },
  t: 'event',
  uniqueid: '00:15:8d:00:03:56:a3:8c-01-0b04' }
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-motion] AqaraMotionDriver has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-motion] [0] Kledingkamer sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-motion] [1] Zolder sensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-motion] [2] Schuursensor has been initiated
2019-12-06 22:50:40 [log] [ManagerDrivers] [aqara-motion] [3] Trap sensor has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-motion] [4] Kledingkamer sensor 2 has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-motion] [5] Hal sensor has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-motion] [6] Voordeur sensor has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-motion] [7] Keuken sensor has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [plug] PlugDriver has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [plug] [0] Beamer has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [plug] [1] Monitor has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [plug] [2] Konijnenhok has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [plug] [3] Zonnebank has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [plug] [4] Lampen & Radio schuur has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [plug] [5] Telefoonoplader has been initiated
2019-12-06 22:50:41 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '12',
  r: 'sensors',
  state: { consumption: 140, lastupdated: '2019-12-06T21:50:41' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:56:a3:8c-01-0702' }
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-temphum] AqaraTempHumDriver has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-temphum] [0] Temperatuur badkamer has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-temphum] [1] Temperatuur slaapkamer has been initiated
2019-12-06 22:50:41 [log] [ManagerDrivers] [aqara-temphum] [2] Temperatuur keuken has been initiated
2019-12-06 22:50:44 [log] [deCONZ] state update for Mi Magic Cube { buttonevent: 6694,
  gesture: 7,
  lastupdated: '2019-12-06T21:50:44' }
2019-12-06 22:50:44 [log] [ManagerDrivers] [aqara-cube] [0] 4 9 6 6
2019-12-06 22:50:44 [log] [ManagerDrivers] [aqara-cube] [0] rotated 6694
2019-12-06 22:50:48 [log] [deCONZ] state update for Mi Magic Cube { buttonevent: 7343,
  gesture: 7,
  lastupdated: '2019-12-06T21:50:48' }
2019-12-06 22:50:48 [log] [ManagerDrivers] [aqara-cube] [0] 3 4 3 7
2019-12-06 22:50:48 [log] [ManagerDrivers] [aqara-cube] [0] rotated 7343
2019-12-06 22:50:48 [log] [deCONZ] state update for Mi Magic Cube { buttonevent: 7472,
  gesture: 7,
  lastupdated: '2019-12-06T21:50:48' }
2019-12-06 22:50:48 [log] [ManagerDrivers] [aqara-cube] [0] 2 7 4 7
2019-12-06 22:50:48 [log] [ManagerDrivers] [aqara-cube] [0] rotated 7472
2019-12-06 22:50:48 [log] [deCONZ] state update for Hue woonkamer sensor { lastupdated: '2019-12-06T21:50:48', presence: false }
2019-12-06 22:50:48 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '2',
  r: 'sensors',
  state: { consumption: 210, lastupdated: '2019-12-06T21:50:48' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:28:33:f6-01-0702' }
2019-12-06 22:50:54 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '4',
  r: 'sensors',
  state: { consumption: 0, lastupdated: '2019-12-06T21:50:54' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:fe:0a:62-01-0702' }
2019-12-06 22:50:57 [log] [deCONZ] state update for Hue keuken sensor { dark: true,
  daylight: false,
  lastupdated: '2019-12-06T21:50:57',
  lightlevel: 0,
  lux: 0 }
(node:32450) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:32450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32450) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-12-06 22:50:59 [log] [deCONZ] state update for Hue badkamer sensor { lastupdated: '2019-12-06T21:50:59', presence: false }
2019-12-06 22:51:01 [log] [deCONZ] state update for Beamer { current: 0,
  lastupdated: '2019-12-06T21:51:01',
  power: 0,
  voltage: 245 }
2019-12-06 22:51:01 [log] [deCONZ] state update for Konijnenhok { current: 30,
  lastupdated: '2019-12-06T21:51:01',
  power: 3,
  voltage: 242 }
2019-12-06 22:51:02 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '8',
  r: 'sensors',
  state: { consumption: 1100, lastupdated: '2019-12-06T21:51:02' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:1e:e4:ab-01-0702' }
2019-12-06 22:51:02 [log] [deCONZ] state update for Hue badkamer sensor { dark: true,
  daylight: false,
  lastupdated: '2019-12-06T21:51:02',
  lightlevel: 0,
  lux: 0 }
(node:32450) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:32450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-12-06 22:51:06 [log] [deCONZ] state update for Overloop sensor { lastupdated: '2019-12-06T21:51:06', presence: false }
2019-12-06 22:51:07 [log] [deCONZ] state update for Lampen & Radio schuur { current: 0,
  lastupdated: '2019-12-06T21:51:07',
  power: 0,
  voltage: 245 }
2019-12-06 22:51:08 [log] [deCONZ] state update for Zonnebank { current: 0,
  lastupdated: '2019-12-06T21:51:08',
  power: 0,
  voltage: 242 }
2019-12-06 22:51:08 [log] [deCONZ] state update for Zonnebank { current: 0,
  lastupdated: '2019-12-06T21:51:08',
  power: 0,
  voltage: 242 }
2019-12-06 22:51:09 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '10',
  r: 'sensors',
  state: { consumption: 140, lastupdated: '2019-12-06T21:51:09' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:27:3d:aa-01-0702' }
/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCard.js:1
(function (exports, require, module, __filename, __dirname) { const querystring=require("querystring"),Homey=require("homey"),{callbackify:callbackify}=require("util");class FlowCard extends Homey.SimpleClass{constructor(t){if(super(),this.id=t,this.type=null,this instanceof Homey.FlowCardTrigger?this.type="trigger":this instanceof Homey.FlowCardCondition?this.type="condition":this instanceof Homey.FlowCardAction&&(this.type="action"),!this.type)throw new Error("FlowCard must be an instance of one of the following: FlowCardTrigger, FlowCardCondition or FlowCardAction");if(!Homey.manifest.flow||!Array.isArray(Homey.manifest.flow[`${this.type}s`]))throw new Error(`flow.${this.type}s does not exist in the app.json config or is not an Array`);if(this._cardObj=Homey.manifest.flow[`${this.type}s`].find(t=>t.id===this.id),void 0===this._cardObj)throw new Error("Invalid card id");this._args={},this._runListener=void 0,this._cardObj.args

Error: Invalid card id
    at new FlowCard (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCard.js:1:857)
    at new FlowCardTrigger (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCardTrigger.js:1:152)
    at new FlowCardTriggerDevice (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCardTriggerDevice.js:1:165)
    at AqaraButtonGyro.setTriggers (/drivers/aqara-button-gyro/device.js:41:24)
    at AqaraButtonGyro.onInit (/drivers/aqara-button-gyro/device.js:11:8)
    at AqaraButtonGyro.__onInit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:1831)
    at emitNone (events.js:106:13)
    at AqaraButtonGyro.emit (events.js:208:7)
    at ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2612)
    at AqaraButtonGyroDriver.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:4653)

--- INFO: ru.notabene.deconz has been killed ---

**Comment by powermarcel10** [comment]
There it is. Immediately after adding the switch te app crashes.

**Comment by notabene00** [comment]
My bad. Trigger id was just `shake`, but inside of `device.js` I used `shaked`
Fixed

**Comment by powermarcel10** [comment]
> My bad. Trigger id was just `shake`, but inside of `device.js` I used `shaked`
> Fixed

Great you found the issue so fast! Will try the new test version ASAP.

**Comment by powermarcel10** [comment]
Still crashing:

Microsoft Windows [Version 10.0.18362.476]
(c) 2019 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\power>cd C:\CLI\HomeyCONZ-aqara-buttons

C:\CLI\HomeyCONZ-aqara-buttons>homey app install
✓ Pre-processing app...
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
 — App size: 861.5 KB
✓ Installing Homey App on `Homey` (http://192.168.0.131:80)...
✓ Homey App `ru.notabene.deconz` successfully installed

C:\CLI\HomeyCONZ-aqara-buttons>homey app run
✓ Pre-processing app...
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
 — App size: 861.5 KB
✓ Installing Homey App on `Homey` (http://192.168.0.131:80)...
✓ Homey App `ru.notabene.deconz` successfully installed
✓ Running `ru.notabene.deconz`, press CTRL+C to quit
 — Profile your app's performance at https://go.athom.com/app-profiling?homey=5808953c1b4ad29575d05156&app=ru.notabene.deconz
─────────────── Logging stdout & stderr ───────────────
2019-12-07 15:05:59 [log] [deCONZ] Websocket connect...
2019-12-07 15:05:59 [log] [deCONZ] Websocket is up
2019-12-07 15:05:59 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '9',
  r: 'sensors',
  state:
   { current: 0,
     lastupdated: '2019-12-07T14:05:59',
     power: 0,
     voltage: 241 },
  t: 'event',
  uniqueid: '00:15:8d:00:03:1e:e4:ab-01-0b04' }
2019-12-07 15:06:00 [log] [ManagerDrivers] [tradfri-square-dimmer] TradfriSquareDimmerDriver has been inited
2019-12-07 15:06:00 [log] [ManagerDrivers] [sensor_smoke] SmokeDriver has been initiated
2019-12-07 15:06:00 [log] [ManagerDrivers] [mi-magnet] MiMagnetDriver has been initiated
2019-12-07 15:06:01 [log] [ManagerDrivers] [aqara-button-gyro] AqaraButtonGyroDriver has been initiated
2019-12-07 15:06:01 [log] [ManagerDrivers] [mi-button] MiButtonDriver has been initiated
2019-12-07 15:06:01 [log] [ManagerDrivers] [tradfri-wireless-dimmer] TradfriWirelessDimmerDriver has been inited
2019-12-07 15:06:01 [log] [ManagerDrivers] [symfonisk-remote] SymfoniskRemoteDriver has been initiated
2019-12-07 15:06:02 [log] [ManagerDrivers] [tradfri-motion-sensor] TradfriMotionSensorDriver has been initiated
2019-12-07 15:06:03 [log] [ManagerDrivers] [leakage_aq1] LeakageDriver has been initiated
2019-12-07 15:06:03 [log] [ManagerDrivers] [blinds] BlindsDriver has been initiated
2019-12-07 15:06:04 [log] [ManagerDrivers] [mijia-temphum] MijiaTempHumDriver has been initiated
2019-12-07 15:06:06 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '10',
  r: 'sensors',
  state: { consumption: 160, lastupdated: '2019-12-07T14:06:01' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:27:3d:aa-01-0702' }
2019-12-07 15:06:06 [log] [ManagerDrivers] [tradfri-remote-control] TradfriRemoteControlDriver has been inited
2019-12-07 15:06:06 [log] [ManagerDrivers] [tradfri-remote-control] [0] TRÅDFRI remote control has been inited
2019-12-07 15:06:07 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '7',
  r: 'sensors',
  state:
   { current: 0,
     lastupdated: '2019-12-07T14:06:07',
     power: 0,
     voltage: 240 },
  t: 'event',
  uniqueid: '00:15:8d:00:03:27:0d:65-01-0b04' }
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] AqaraMagnetDriver has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] [0] Voordeur has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] [1] Halkastdeur has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] [2] Brievenbus has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] [3] Keukenkastdeur has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] [4] Schuurdeur has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] [5] Achterdeur has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-magnet] [6] Zolderdeur has been initiated
2019-12-07 15:06:08 [log] [ManagerDrivers] [aqara-cube] CubeDriver has been initiated
/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCard.js:1
(function (exports, require, module, __filename, __dirname) { const querystring=require("querystring"),Homey=require("homey"),{callbackify:callbackify}=require("util");class FlowCard extends Homey.SimpleClass{constructor(t){if(super(),this.id=t,this.type=null,this instanceof Homey.FlowCardTrigger?this.type="trigger":this instanceof Homey.FlowCardCondition?this.type="condition":this instanceof Homey.FlowCardAction&&(this.type="action"),!this.type)throw new Error("FlowCard must be an instance of one of the following: FlowCardTrigger, FlowCardCondition or FlowCardAction");if(!Homey.manifest.flow||!Array.isArray(Homey.manifest.flow[`${this.type}s`]))throw new Error(`flow.${this.type}s does not exist in the app.json config or is not an Array`);if(this._cardObj=Homey.manifest.flow[`${this.type}s`].find(t=>t.id===this.id),void 0===this._cardObj)throw new Error("Invalid card id");this._args={},this._runListener=void 0,this._cardObj.args

Error: Invalid card id
    at new FlowCard (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCard.js:1:857)
    at new FlowCardTrigger (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCardTrigger.js:1:152)
    at new FlowCardTriggerDevice (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCardTriggerDevice.js:1:165)
    at Cube.setTriggers (/drivers/aqara-cube/device.js:53:24)
    at Cube.onInit (/drivers/aqara-cube/device.js:11:8)
    at Cube.__onInit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:1831)
    at emitNone (events.js:106:13)
    at Cube.emit (events.js:208:7)
    at ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2612)
    at CubeDriver.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:4653)

--- INFO: ru.notabene.deconz has been killed ---

**Comment by SkorpionNL** [comment]
A quick glance shows me that there’s an error with a flow card condition of the Aqara Cube. The Gyro Aqara button doesn’t seem to be the culprit here. Unfortunately I don’t have the time to check this out.

**Comment by notabene00** [comment]
> there’s an error with a flow card condition of the Aqara Cube

Oh shi.. Thank you very much
Not condition - trigger, but yes
I have changed trigger id to `shaked`, but not updated cube's `device.js`

I think that modification of the cube's file will lead to the destruction of previously created flows with it
So I changed `shaked` back to `shake` inside of `app.json`
And fixed a card id in the Gyro's `device.js`

I hope I did the right thing

@powermarcel10 can you try?

**Comment by powermarcel10** [comment]
Yeah it's working now! No more crashes! Great job. One very, very small thing to mention: the icon of this gyro switch looks exactly the same as the normal switch. Maybe you can add this icon like it is in the aqara app for homeyb

![IMG_20191208_152841](https://user-images.githubusercontent.com/2340835/70390909-b8f1cb00-19cf-11ea-9a11-bc413f658b58.jpg)

**Comment by powermarcel10** [comment]
Some more info I found: Maybe interesting

WXKG11LM	original	lumi.sensor_switch.aq2	Single, Double, Triple, & Quad-click
WXKG11LM	new	        lumi.remote.b1acn01	Single/Double-click, Hold, & Release
WXKG12LM		        lumi.sensor_switch.aq3	Single/Double-click, Hold, Release, & Shake

**Comment by notabene00** [comment]
> WXKG11LM	new	lumi.remote.b1acn01	Single/Double-click, Hold, & Release

If you want this device to be supported, create new request

P.S. _I don't like perspective to add the same device multiple times cuz manufacturer decided to cut off some capabilities and sell it as a new. But it seems we have no choice. Shame on you, Aqara_
